version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      submodule-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
