[tools]
uv = "latest"
rust = { version = "stable", profile = "default", components = "rust-src" }
npm = "latest"
node = "lts"

[tasks.setup]
sources = ["mise.toml"]
run = "mise install"

[tasks.uv-sync]
sources = ["pyproject.toml", "uv.lock"]
depends = ["setup"]
run = "uv sync"

[tasks.npm-sync]
sources = ["package.json", "package-lock.json"]
depends = ["setup"]
run = "npm ci"

[tasks.sync]
depends = ["uv-sync", "npm-sync"]

[tasks.rust-format]
sources = ["src/**/*.rs"]
run = "cargo fmt --all"

[tasks.python-format]
sources = ["examples/**/*.py", "tests/**/*.py", "torchfont/**/*.py"]
depends = ["uv-sync"]
run = "uv run ruff format"

[tasks.format]
depends = ["rust-format", "python-format"]

[tasks.rust-check]
sources = ["Cargo.toml", "Cargo.lock", "src/**/*.rs"]
run = [
  "cargo fmt --all -- --check",
  "cargo clippy --all-targets --all-features -- -D warnings",
  "cargo check --all-targets --all-features",
]

[tasks.python-check]
sources = [
  "pyproject.toml",
  "uv.lock",
  "examples/**/*.py",
  "tests/**/*.py",
  "torchfont/**/*.py",
]
depends = ["uv-sync"]
run = ["uv run ruff format --check", "uv run ruff check", "uv run ty check"]

[tasks.check]
depends = ["rust-check", "python-check"]

[tasks.build]
sources = [
  "Cargo.toml",
  "Cargo.lock",
  "pyproject.toml",
  "uv.lock",
  "src/**/*.rs",
  "torchfont/**/*.py",
]
depends = ["check"]
run = "uv run maturin develop --release"

[tasks.test]
depends = ["build"]
run = "uv run pytest tests"

[tasks.docs-build]
sources = ["docs/**/*", "package.json", "package-lock.json"]
depends = ["npm-sync"]
run = "npm run docs:build"

[tasks.data-sync]
run = [
  "git submodule sync --recursive",
  "git submodule update --init --depth 1 --recursive",
]

[tasks.data-update]
run = [
  "git submodule sync --recursive",
  "git submodule update --remote --depth 1 --recursive",
]
